name: Check for broken links

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v2
        with:
          args: README.md --accept "100..=103,200..=299,403" --timeout 60
          fail: true